### ISSUE TITLE
Using Pose2Point2Bearing in Hexagonal causes solver error

### ISSUE THREAD

**Issue by GearsAD** [JuliaRobotics/RoME.jl#116]
When using the Pose2Point2Bearing as landmark factor in Hexagonal example, two factors are added (x0l1 and x6l1). As the 2nd factor is added, a solver error is thrown. 

There's a small example in the fixpose2point2brsample branch https://github.com/JuliaRobotics/RoME.jl/blob/hotfix/fixpose2point2brsample/examples/Hexagonal2D_BearingOnly_SLAM.jl

```
During the resolution of the non-linear system, the evaluation of the following equation(s) resulted in a non-finite number: [1]
in anonymous at base/<missing>
in macro expansion at Hexagonal2D_BearingOnly_SLAM.jl:45 
in addFactor! at IncrementalInference/src/FactorGraph01.jl:634
in #addFactor!#53 at IncrementalInference/src/FactorGraph01.jl:638
in  at base/<missing>
in #addFactor!#52 at IncrementalInference/src/FactorGraph01.jl:609
in  at base/<missing>
in #doautoinit!#45 at IncrementalInference/src/FactorGraph01.jl:497
in  at base/<missing>
in #predictbelief#136 at IncrementalInference/src/SolveTree01.jl:338
in  at base/<missing>
in #predictbelief#135 at IncrementalInference/src/SolveTree01.jl:313
in  at base/<missing>
in #proposalbeliefs!#134 at IncrementalInference/src/SolveTree01.jl:282
in findRelatedFromPotential at IncrementalInference/src/ApproxConv.jl:381
in  at base/<missing>
in #evalFactor2#130 at IncrementalInference/src/ApproxConv.jl:333
in  at base/<missing>
in #evalPotentialSpecific#127 at IncrementalInference/src/ApproxConv.jl:225
in computeAcrossHypothesis! at IncrementalInference/src/ApproxConv.jl:125
in approxConvOnElements! at IncrementalInference/src/ApproxConv.jl:68
in approxConvOnElements! at IncrementalInference/src/ApproxConv.jl:46
in #numericRootGenericRandomizedFnc!#114 at IncrementalInference/src/SolverUtilities.jl:94
in #nlsolve#39 at NLsolve/src/nlsolve/nlsolve.jl:59
in  at base/<missing>
in #nlsolve#38 at NLsolve/src/nlsolve/nlsolve.jl:26
in trust_region_ at NLsolve/src/solvers/trust_region.jl:120
in check_isfinite at NLsolve/src/nlsolve/utils.jl:35
```

**Comment by dehann** [comment]
Hi, thanks -- right, this looks like the solver is hunting around for a solution but not able to adjust the landmark or pose variables to resolve the residual function.

I see two issues with the current implementation of `Pose2Point2Bearing` -- guess this [code got a little outdated](https://github.com/JuliaRobotics/RoME.jl/blob/2b5a57a20ff1f390e76c01ae0f4f84d217cd4a13/src/BearingRange2D.jl#L94).

Todo's are:
- [ ] change to `FunctorPairwiseMinimize`,
- [ ] rather use `SamplableBelief` over just `Distribution`.

Will get on it soon, I'm just busy getting code to run on Julia 0.7 and 1.0 also.  Will bundle this fix with that release.
