### ISSUE TITLE
preallocate rotation matrix for Pose2 operations

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/RoME.jl#184]
A test suggests there are 18 allocations within each `AMP.difftheta` operation.

**Comment by mc2922** [comment]
This should be 0 allocations for difftheta, although requires preallocating the transform matrix:

```
function difftheta2(wth1::Float64, wth2::Float64, Rtemp::Matrix{Float64})
    Rtemp[1,1] = cos(wth1)*cos(wth2)+sin(wth1)*sin(wth2)
    Rtemp[1,2] = cos(wth1)*-sin(wth2)+sin(wth1)*cos(wth2)
    Rtemp[2,1] = -sin(wth1)*cos(wth2)+cos(wth1)*sin(wth2)
    Rtemp[2,2] = -sin(wth1)*-sin(wth2)+cos(wth1)*cos(wth2)
    logmap_SO2(Rtemp)
end
```

**Comment by dehann** [comment]
Awesome thanks, I will add this soon!

**Comment by Affie** [comment]
I think this is no longer relevant with Manifolds.jl upgrade.  The current plan is to work towards static arrays for zero allocations.
