### ISSUE TITLE
PackageCompiler.jl for .so compiling

### ISSUE THREAD

**Issue by dehann** [JuliaRobotics/RoME.jl#288]
Compile an in-memory version of RoME.jl as static object that can be included in C++ programs like a regular old-school .so library.  Regular features like this should be doable, and its okay to start small:
```julia
initfg
addVariable!
addFactor!
solveTree!
Pose2
Point2
PriorPose2
Pose2Pose2
```

Additional FAQ:
https://juliarobotics.org/Caesar.jl/latest/faq/#Static,-Shared-Object-.so-Compilation-1

cc @GearsAD

**Comment by Affie** [comment]
Some references
Julia
https://docs.julialang.org/en/v1/manual/embedding/

PackageCompiler.jl
https://julialang.github.io/PackageCompiler.jl/dev/sysimages/
https://github.com/JuliaLang/PackageCompiler.jl/issues/257#issuecomment-614658462
https://github.com/JuliaLang/PackageCompiler.jl/issues/393
