### ISSUE TITLE
Implement getParametricMeasurement where needed

### ISSUE THREAD

**Issue by Affie** [JuliaRobotics/RoME.jl#382]
We need to implement `getParametricMeasurement` for all factors that need it. 
The fallback is to use the .Z or .z field, with a warning (warn once) and link to the documentation.

- [x] Pose2Point2BearingRange
https://github.com/JuliaRobotics/RoME.jl/blob/83f9b2f8b3cd60219c00370439024bc04166e40c/src/factors/BearingRange2D.jl#L10-L13 see #384

**Comment by dehann** [comment]
Check what i did in IIF, assuming you trying to get mean and cov?

**Comment by dehann** [comment]
either way, i think best is to get parametric to use the same factor (even if helpers like getParametricField are needed) just to get consolidation doen and close IIF 467.  Likely multiple rounds of improvements to do here, so let's do baby steps by consolidate one each?

**Comment by Affie** [comment]
We are going with extending `getParametricMeasurement` instead, see #384

**Comment by Affie** [comment]
#393 implements and tests some factors, rest can be done as needed.
