### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by mc2922** [JuliaRobotics/RoME.jl#59]
Is this the right model for package dependencies?

IncrementalInference -> RoME -> Caesar -> Arena
|
-> RoMEPlotting? 

Related? These warnings:
```julia
WARNING: both IncrementalInference and RoME export "compare"; uses of it in module Main must be qualified
WARNING: both IncrementalInference and RoME export "evalPotential"; uses of it in module Main must be qualified
```

**Comment by dehann** [comment]
Hi,

Yes, so [`IncrementalInference.jl`](http://www.github.com/JuliaRobotics/IncrementalInference.jl) supplies the algebraic logic for factor graph inference with Bayes tree and depends on several packages itself.  [`RoME.jl`](http://www.github.com/JuliaRobotics/RoME.jl) introduces nodes and factors that are useful to robotic navigation.  [`RoMEPlotting.jl`](http://www.github.com/JuliaRobotics/RoMEPlotting.jl) are a set of scripts that provide MATLAB style plotting of factor graph beliefs, mostly supporting 2D visualization with some support for projections of 3D.  

[`Caesar.jl`](http://www.github.com/JuliaRobotics/Caesar.jl) is the umbrella repo that depends on `RoME.jl` and others to support that 'passes through' the same functionality while introducing more.  For example, interaction with database server systems, [`LCMCore.jl`](http://www.github.com/JuliaRobotics/LCMCore.jl), (future ROS support), and more. 

[`Arena.jl`](http://www.github.com/JuliaRobotics/Arena.jl) is a collection of 3D visualization tools and also depends on `RoMEPlotting.jl` for 2D visualizations.

At the time of writing this there have been a lot of changes / refactoring / improvements to the cumulative code base.  Most notably the migration to [JuliaRobotics](http://www.github.com/JuliaRobotics/) and the upcoming separate of [`DistributedFactorGraphs.jl`](http://www.github.com/JuliaRobotics/DistributedFactorGRaphs.jl).

In the future, `Caesar.jl` would likely interact more closely with repo's such as [`SensorFeatureTracking.jl`](http://www.github.com/JuliaRobotics/SensorFeatureTracking.jl), [`AprilTags.jl`](http://www.github.com/JuliaRobotics/AprilTags.jl), and `RecursiveFiltering`.

Thanks, those warnings will be removed in due course, they are not immediately serious.
